name: Test

on:
  push:
    branches:
      - 3.*
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      # Obtención del código
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # Instalación de dependencias
      - name: Preparar Python v3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Instalar dependencias de sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-es gettext language-pack-es
      - name: Instalar dependencias de Python
        run: |
          python -m pip install -r requirements.txt
      - name: Listar paquetes y versiones
        run: |
          pip list
          pospell --version
          powrap --version

      # Chequeos a realizar
      - name: TRANSLATORS
        run: |
          diff -Naur TRANSLATORS <(LANG=es python scripts/sort.py < TRANSLATORS)
      - name: Powrap
        run: powrap --check --quiet **/*.po
      - name: Sphinx lint
        run: |
          sphinx-lint */*.po
      - name: Pospell
        run: |
          python scripts/check_spell.py

      # Construcción de la documentación
      - name: Construir documentación
        run: |
          # FIXME: Relative paths for includes in 'cpython'
          sed -i -e 's|.. include:: ../includes/wasm-notavail.rst|.. include:: ../../../../includes/wasm-notavail.rst|g' cpython/Doc/**/*.rst
          sed -i -e 's|.. include:: ../distutils/_setuptools_disclaimer.rst|.. include:: ../../../../distutils/_setuptools_disclaimer.rst|g' cpython/Doc/**/*.rst
          sed -i -e 's|.. include:: ./_setuptools_disclaimer.rst|.. include:: ../../../_setuptools_disclaimer.rst|g' cpython/Doc/**/*.rst
          sed -i -e 's|.. include:: token-list.inc|.. include:: ../../../token-list.inc|g' cpython/Doc/**/*.rst
          sed -i -e 's|.. include:: ../../using/venv-create.inc|.. include:: ../using/venv-create.inc|g' cpython/Doc/**/*.rst
          sed -i -e 's|.. include:: ../../../using/venv-create.inc|.. include:: ../../using/venv-create.inc|g' cpython/Doc/**/*.rst
          sed -i -e 's|.. include:: /using/venv-create.inc|.. include:: ../../../../using/venv-create.inc|g' cpython/Doc/**/*.rst
          # Normal build
          PYTHONWARNINGS=ignore::FutureWarning,ignore::RuntimeWarning sphinx-build -j auto -W --keep-going -b html -d cpython/Doc/_build/doctree -D language=es . cpython/Doc/_build/html
